apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-deployment
  namespace: laravel-mysql
  labels:
    app: laravel
spec:
  selector:
    matchLabels:
      app: laravel
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers: 
      - name: laravel-container
        image: gerrome/recipeapp-laravel
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: laravel-mysql
  labels:
    app: laravel
spec:
  type: ClusterIP
  selector:
    app: laravel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080