version: '3.9'

services:
  backend:
    container_name: dotnet-container
    build: .
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: postgres-container
    image: postgres:latest
    env_file:
      - .envdocker
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  db-data: