apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-deployment
  namespace: dotnet-postgres
  labels:
    app: dotnet
spec:
  selector:
    matchLabels:
      app: dotnet
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: django
    spec:
      containers: 
      - name: dotnet-container
        image: gerrome/recipeapp-dotnet
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
  namespace: dotnet-postgres
  labels:
    app: dotnet
spec:
  type: ClusterIP
  selector:
    app: dotnet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000