version: '3.9'

services:
  frontend:
    container_name: react-app
    build: ./ComputexFrontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - frontend_network

  backend:
    container_name: django-app
    build: ./ComputexBackend
    ports:
      - "8000:8000"
    networks:
      - backend_network
      - frontend_network      
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: postgres-container
    image: postgres:latest
    env_file:
      - .envdocker
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - backend_network      

volumes:
  db-data:

networks:
  frontend_network:
  backend_network: