apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  namespace: node-mongo
  labels:
    app: node
spec:
  selector:
    matchLabels:
      app: node
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: node
    spec:
      containers: 
      - name: node-container
        image: gerrome/recipeapp-node
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: node-mongo
  labels:
    app: node
spec:
  type: ClusterIP
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000