version: '3.9'

services:

  backend:
    container_name: express-container
    build: . 
    ports:
      - "5000:5000"
    depends_on:
      database:
          condition: service_healthy

  database:
    container_name: mongo-container
    image: mongo:5.0
    env_file:
      - .envdocker
    expose: 
      - 27017
    volumes:
      - db-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  db-data: