global:
  scrape_interval: 1m
  external_labels:
    monitor: 'docker-container-monitor'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 34.16.183.88:9093
      
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
  - job_name: "node"
    static_configs:
      - targets: ["10.182.0.2:9100"]
  - job_name: "alertmanager"
    static_configs:
      - targets: ["34.16.183.88:9093"] 

rule_files:
  - 'alert.rules.yml'
  - 'rules.yml' 
