apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  namespace: java-mysql
  labels:
    app: java
spec:
  selector:
    matchLabels:
      app: java
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: java
    spec:
      containers: 
      - name: java-container
        image: gerrome/recipeapp-java
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: java-service
  namespace: java-mysql
  labels:
    app: java
spec:
  type: ClusterIP
  selector:
    app: java
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080