version: '3.9'

services:
  backend:
    depends_on:
      database:
          condition: service_healthy
    container_name: laravel-container
    build: .
    ports:
      - "8080:8080"

  database:
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    container_name: mysql-container
    image: mysql:8
    env_file:
      - .envdocker 
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
volumes:
  db: