route:
  group_by: ['alertname', 'severity']
  group_wait: 3s
  group_interval: 10s
  repeat_interval: 5m
  receiver: 'kenDevopsTest-email'

receivers:
  - name: 'kenDevopsTest-email'
    email_configs:
      - send_resolved: true
        to: 'kennethnwankwo@soundtechworks.com.ng'
        from: 'alertmanager@soundtechworks.com.ng'
        smarthost: 'standard15.doveserver.com:465'
        auth_username: 'alertmanager@soundtechworks.com.ng'
        auth_password: 'Pilot500'
        require_tls: false
