- name: Setup Monitoring and Logging Solution (Prometheus-Grafana-Loki)
  hosts:
    - slave
  become: true
  vars:
    app_dir: /home/ubuntu/appdir
    monitoring_dir: /home/ubuntu/Monitoring-Logging

  tasks:

    - name: Clone monitoring repo
      git:
        repo: https://github.com/GerromeSieger/Monitoring-Logging.git
        dest: '{{ monitoring_dir }}'
        force: 'yes'

    - name: Deploy docker-compose for monitoring
      community.docker.docker_compose:
        project_src: '{{ monitoring_dir }}'
        state: present

    - name: Check if loki plugin is installed
      command: docker plugin ls
      register: plugin_list
      changed_when: false

    - name: Install loki plugin
      command: docker plugin install grafana/loki-docker-driver:latest --alias loki
        --grant-all-permissions
      when: '''loki'' not in plugin_list.stdout'

    - name: Check if daemon.json exists
      stat:
        path: /etc/docker/daemon.json
      register: daemon_json

    - name: Configure daemon.json
      blockinfile:
        path: /etc/docker/daemon.json
        create: 'yes'
        block: |
          {
              "log-driver": "loki",
              "log-opts": {
                  "loki-url": "http://localhost:3100/loki/api/v1/push",
                  "loki-batch-size": "400"
              }
          }
      when: not daemon_json.stat.exists
      register: daemon_json_configured

    - name: Restart Docker
      service:
        name: docker
        state: restarted
        enabled: 'yes'
      when: daemon_json_configured.changed

    - name: Deploy application
      community.docker.docker_compose:
        project_src: '{{ app_dir }}'
        state: present
        recreate: always
      when: daemon_json_configured.changed

    - name: Redeploy monitoring
      community.docker.docker_compose:
        project_src: '{{ monitoring_dir }}'
        state: present
        recreate: always
      when: daemon_json_configured.changed