---
- name: DEPLOYING REACT APP
  hosts: [slave1]
  become: true

  tasks:
    - name: Get Updates
      apt:
        update_cache: yes 

    - name: Check if Node.js repo is already configured
      stat:
        path: /etc/apt/sources.list.d/nodesource.list
      register: node_repo

    - name: Add Node.js 18.x repository
      shell: curl -sL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh && sudo bash nodesource_setup.sh
      when: not node_repo.stat.exists

    - name: Install Node.js & Nginx
      apt:
        name:
          - nodejs
          - nginx
          - yarn
        state: latest

    - name: Clone repo
      git:
        repo: https://github.com/bradtraversy/feedback-app.git
        dest: /home/ubuntu/feedback-app
        clone: yes

    - name: Install dependencies with yarn
      command: cd /home/ubuntu/feedback-app && yarn install

    - name: Build app
      command: cd /home/ubuntu/feedback-app && yarn build

    - name: Copy build folder to /var/www/html
      command: sudo cp -r /home/ubuntu/feedback-app/build/* /var/www/html

    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted