apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus-community
  name: mysm
spec:
  endpoints:
  - interval: 30s
    port: web
  selector:
    matchLabels:
      app: example-app