apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-deployment
  namespace: default
  labels:
    app: next
spec:
  selector:
    matchLabels:
      app: next
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: next
    spec:
      containers:
      - name: nextapp-container
        image: gerrome/next-site
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: next-service
  namespace: default
  labels:
    app: next
spec:
  type: ClusterIP
  selector:
    app: next
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000