apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-deployment
  namespace: default
  labels:
    app: vue
spec:
  selector:
    matchLabels:
      app: vue
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: vue
    spec:
      containers:
      - name: vue-container
        image: gerrome/vue-site
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vue-service
  namespace: default
  labels:
    app: vue
spec:
  type: ClusterIP
  selector:
    app: vue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80