apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
#  namespace: test
type: Opaque
data: 
  user: YWRtaW4=
  password: MTIzNDU=
  database: Y29tcHV0ZXg=

# echo -n 'admin' | base64 (command to encode in base64)  