version: 2.1

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: main
      - build:
          requires:
            - test
          filters:
            branches:
              only: main            
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main

jobs:
  test:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: Run SonarQube analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=${PROJECT_KEY} \
              -Dsonar.sources=. \
              -Dsonar.host.url=${SONAR_HOST_URL} \
              -Dsonar.login=${SONAR_TOKEN}

  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and push Docker image
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t $DOCKER_IMAGE .
            docker push $DOCKER_IMAGE

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "${SSH_KEY_FINGERPRINT}"
      - run:
          name: Setup SSH and deploy
          command: |
            ssh -o StrictHostKeyChecking=no $USER@$HOST '
                docker pull gerrome/vue-site
                docker run -p 8080:80 -d gerrome/vue-site
              '