jobs:

  build: 
    - uses: actions/upload-artifact@v1
      with:
        name: react-app
        path: build

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v3
      with: 
        name: react-app
        path: build
        
    - name: Copy files to server  
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }} 
        source: "build"
        target: "/var/www/html"

    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          sudo systemctl restart nginx