name: React-Site-Workflow/Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build

      - uses: actions/upload-artifact@v1
        with:
          name: react-app
          path: build           

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with: 
          name: react-app
          path: build

      - name: Run Shell script for testing
        run: sh test.sh

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v3
      with: 
        name: react-app
        path: build
        
    - name: Copy files to server  
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }} 
        source: "build"
        target: "/home/ubuntu"

    - name: Ssh into the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          sudo cp -r build/* /var/www/html
          sudo systemctl restart nginx